version: '3.10'

services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080